version: "3.8"

services:
  frontend:
    build:
      context: ./store-management-frontend-app
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    environment:
      - VUE_APP_API_BASE_URL=http://127.0.0.1:5000
