name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_JSON }}
          project_id: store-management-2024

      # Step 3: Ensure ./src Directory Exists
      - name: Ensure ./src Exists
        run: |
          if [ ! -d "./src" ]; then
            echo "Directory ./src does not exist. Creating it..."
            mkdir -p ./src
            # Optionally add placeholder files
            echo "This is a placeholder file for ./src" > ./src/placeholder.txt
          else
            echo "Directory ./src exists."
          fi

      # Step 4: Build the Application
      - name: Build the Application
        run: |
          mkdir build
          tar -czf build/app.tar.gz ./src
          echo "Application build completed."

      # Step 5: Authenticate with Google Cloud using the Service Account Key
      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY_JSON }}" > /tmp/gcloud-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json
          gcloud config set project store-management-2024
          echo "Authentication completed."

      # Step 6: Generate Signed URL for Artifact Upload
      - name: Generate Signed URL for Artifact Upload
        run: |
          echo "Generating signed URL for artifact upload..."
          gsutil signurl -d 1h /tmp/gcloud-key.json gs://store-management-bucket-12345/src/app.tar.gz > signed_url.txt
          export SIGNED_URL=$(cat signed_url.txt)
          echo "Signed URL generated."

      # Step 7: Upload Artifact to GCS using Signed URL
      - name: Upload Artifact to Google Cloud Storage (GCS) using Signed URL
        run: |
          echo "Uploading artifact to Google Cloud Storage..."
          curl -X PUT -T build/app.tar.gz "$SIGNED_URL"
          echo "Artifact uploaded successfully."

      # Step 8: Complete Job
      - name: Complete Job
        run: echo "CI/CD pipeline completed successfully!"
