name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: store-management-2024

      # Step 3: Ensure ./src Directory Exists
      - name: Ensure ./src Exists
        run: |
          if [ ! -d "./src" ]; then
            echo "Directory ./src does not exist. Creating it..."
            mkdir -p ./src
            # Optionally add placeholder files
            echo "This is a placeholder file for ./src" > ./src/placeholder.txt
          else
            echo "Directory ./src exists."
          fi

      # Step 4: Build the Application
      - name: Build the Application
        run: |
          echo "Building the application..."
          mkdir build
          tar -czf build/app.tar.gz ./src
          echo "Application built successfully and archived to build/app.tar.gz."

      # Step 5: Ensure GCS Path is Accessible
      - name: Ensure GCS Path is Accessible
        run: |
          echo "Checking access to gs://store-management-bucket-12345/src/..."
          if ! gsutil ls gs://store-management-bucket-12345/src/; then
            echo "Error: Unable to access GCS bucket or insufficient permissions."
            echo "Ensure the service account has 'storage.objects.get' permission."
            exit 1
          fi
          echo "GCS path is accessible."


      # Step 6: Upload Artifact to Google Cloud Storage (GCS) with Logging
      - name: Upload Artifact to Google Cloud Storage (GCS) with Logging
        run: |
          echo "Uploading artifact to Google Cloud Storage..."
          gsutil cp build/app.tar.gz gs://store-management-bucket-12345/src/
          echo "Artifact uploaded successfully to gs://store-management-bucket-12345/src/."

      # Step 7: Complete Job
      - name: Complete Job
        run: echo "CI/CD pipeline completed successfully!"
