name: CI/CD Pipeline for Azure Blob Storage and GCP

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production  # Customize as needed

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build the project
        run: |
          cd store-management-frontend-app
          npm install
          npm run build

      # Step 4: Log in to Azure using Service Principal
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 5: Upload build artifacts to Azure Blob Storage
      - name: Upload artifacts to Azure Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --destination ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} \
            --source ./store-management-frontend-app/

      # Step 6: Set up GCP VM for build process
      - name: Set up GCP VM
        run: |
          # Install Google Cloud SDK
          curl -sSL https://sdk.cloud.google.com | bash
          source ~/.bashrc

          # Authenticate with Google Cloud
          echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json

          # Set GCP project
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

          # SSH into GCP VM and trigger build process
          gcloud compute ssh ${{ secrets.GCP_VM_NAME }} --zone ${{ secrets.GCP_ZONE }} --command "
            cd /opt/store-management-app &&
            npm install &&
            npm run build
          "

      # Step 7: Complete the Job
      - name: Complete Job
        run: echo "CI/CD pipeline completed successfully!"

      # Step 8: Clean up Azure session
      - name: Clean up Azure session
        run: az logout
