name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: store-management-2024

      # Step 3: Ensure ./src Directory Exists
      - name: Ensure ./src Exists
        run: |
          if [ ! -d "./src" ]; then
            echo "Directory ./src does not exist. Creating it..."
            mkdir -p ./src
            # Optionally add placeholder files
            echo "This is a placeholder file for ./src" > ./src/placeholder.txt
          else
            echo "Directory ./src exists."
          fi

      # Step 4: Build the Application
      - name: Build the Application
        run: |
          mkdir build
          tar -czf build/app.tar.gz ./src

      # Step 5: Upload Artifact to GCS
      - name: Upload Artifact to Google Cloud Storage (GCS)
        run: |
          gsutil cp build/app.tar.gz gs://store-management-bucket-12345/src



      # Step 6: Complete Job
      - name: Complete Job
        run: echo "CI/CD pipeline completed successfully!"
