name: CI/CD Pipeline for GCP Deployment

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production  # Customize as needed

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build the project
        run: |
          cd store-management-frontend-app
          npm install
          npm run build

      # Step 4: Log in to Azure using Service Principal (Commented out as per request)
      # - name: Log in to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}  # Azure credentials from a service principal

      # Step 5: (Commented out) Upload build artifacts to Azure Blob Storage
      # - name: Upload artifacts to Azure Blob Storage
      #   run: |
      #     if [ -d "./store-management-frontend-app/dist/" ]; then
      #       az storage blob upload-batch \
      #         --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
      #         --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
      #         --destination ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} \
      #         --source ./store-management-frontend-app/dist/  # Ensure the build output folder is 'dist/'
      #     else
      #       echo "Dist directory does not exist. Check the build step." && exit 1
      #     fi

      # Step 6: SSH into GCP VM, pull the latest code, and deploy with Docker Compose
      - name: Deploy the application on GCP VM using Docker Compose
        run: |
          # Authenticate with Google Cloud
          echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json

          # Set GCP project
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

          # SSH into GCP VM and deploy the application
          gcloud compute ssh ${{ secrets.GCP_VM_NAME }} --zone ${{ secrets.GCP_ZONE }} --command "
            cd /opt/store-management-app &&
            git pull origin main &&  # Ensure the latest version is pulled
            cd Store-Management-System &&  # Navigate to the correct directory
            docker-compose down &&  # Stop any existing containers
            docker-compose up -d   # Start containers using Docker Compose
          "

      # Step 7: Complete the Job
      - name: Complete Job
        run: echo "CI/CD pipeline completed successfully!"

      # Step 8: Clean up Azure session (Commented out as per request)
      # - name: Clean up Azure session
      #   run: az logout
