name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the `main` branch

jobs:
  # Job 1: Build Job
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}   # GCP Project ID stored in GitHub Secrets
        credentials_json: ${{ secrets.GCP_KEY }}   # Service account key stored in GitHub Secrets

    - name: List Directory
      run: ls -R

    # Step 3: Build the artifact
    - name: Build the Application
      run: |
        mkdir build
        tar -czf build/app.tar.gz ./src  # Example: Compress the `src` folder into a tarball

    # Step 4: Upload artifact to GCS
    - name: Upload Artifact to GCS
      run: |
        gsutil cp ./build/app.tar.gz gs://my-deployment-bucket/artifacts/releases/
